# Configuration file for csv_to_bmon.py.  This file is in YAML format,
# see http://camel.readthedocs.io/en/latest/yamlref.html

# interval in seconds to check for new data
check_interval: 30

# BMON URL to post records to
bmon_url: https://bmon.analysisnorth.com/store/

# BMON Store key needed for storing records
bmon_store_key: xyz123

# list of file parsing specifications.  For each spec, 'file_glob' 
# is required and must be a pattern compatible with the Python 
# glob.glob() function.  All other elements are passed to the 
# initialization function of the csv_reader.CSVReader class
csv_files:
  - file_glob: "*.csv"            
    chunk_size: 10
    header_rows: 4
    name_row: 2
    field_map: "lambda nm: '_'.join(nm.split('_')[:2])"
    ts_tz: America/Anchorage
    exclude_fields: [RECORD]
