# Configuration file for csv_transfer.py.  This file is in YAML format,
# see http://camel.readthedocs.io/en/latest/yamlref.html

# True / False.  if True, script runs only once and does not repeatedly
# check for new or updated CSV files.
run_once: True

# If run_once is True, this parameter tells script how many seconds to 
# wait before exiting.
run_once_wait_before_stop: 15

# interval in seconds to check for new data, if running continuously
check_interval: 30

# Logging level for the application.  Should be one of the following
# strings:  CRITICAL, ERROR, WARNING, INFO, DEBUG
logging_level: INFO

# list of file parsing specifications.  For each spec, 'file_glob' 
# is required and must be a pattern compatible with the Python 
# glob.glob() function.  The other possible elements in the spec
# are the parameters to the constructor of the csv_reader.CSVReader
# class in this application.  Any element that does *not* match those 
# constructor parameters is passed on to the csv.reader function found
# in the standard Python csv module, allowing for further configuration
# of the process of reading the csv files.
csv_files:
  - file_glob: "*.csv"            
    chunk_size: 10
    header_rows: 4
    name_row: 2
    field_map: "lambda nm: '_'.join(nm.split('_')[:2])"
    ts_tz: America/Anchorage
    exclude_fields: [RECORD]

# List of consumers of the CSV records
consumers:
  - class_name: bmon_poster.BMONposter
    poster_id:  an-bmon-01              # unique ID for this posting object
    bmon_store_url: https://bmon.analysisnorth.com/readingdb/reading/store/
    bmon_store_key: xyz123
